qcacmn: Fix missing prototypes on parameter-less functions
Clang bail out with some errors :

target_if/core/src/target_if_main.c:91:40: error: a function declaration without a
prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.
hif/src/ce/ce_service_legacy.c:1320:34: error: a function declaration without a
prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.